/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package facadeshop.frame;

/**
 *
 * @author Pedro Baños
 */
public class JFRDetalleCompra extends javax.swing.JFrame {

    /**
     * Creates new form JFRDetalleCompra
     */
    public JFRDetalleCompra() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblMenu = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnCompras = new javax.swing.JButton();
        btnProductos = new javax.swing.JButton();
        btnVentas = new javax.swing.JButton();
        btnProveedores = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jpnIdCompra2 = new javax.swing.JPanel();
        lblIdCompra2 = new javax.swing.JLabel();
        txtIdCompra2 = new javax.swing.JTextField();
        jpnProveedor2 = new javax.swing.JPanel();
        lblProveedor2 = new javax.swing.JLabel();
        txtProveedor2 = new javax.swing.JTextField();
        jpnCabezeraTablaCompra2 = new javax.swing.JPanel();
        lblIdProducto2 = new javax.swing.JLabel();
        lblProducto = new javax.swing.JLabel();
        lblCantidad2 = new javax.swing.JLabel();
        lblCosto2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCompra2 = new javax.swing.JTable();
        jpnFecha2 = new javax.swing.JPanel();
        lblFecha2 = new javax.swing.JLabel();
        jpnIdCompra3 = new javax.swing.JPanel();
        lblIdCompra3 = new javax.swing.JLabel();
        jpnIdCompra4 = new javax.swing.JPanel();
        lblIdCompra4 = new javax.swing.JLabel();
        txtFecha2 = new javax.swing.JTextField();
        jpnTotal2 = new javax.swing.JPanel();
        lblTotal2 = new javax.swing.JLabel();
        txtTotal2 = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(102, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMenu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblMenu.setForeground(new java.awt.Color(255, 255, 255));
        lblMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/facadeshop/icons/mas32.png"))); // NOI18N
        lblMenu.setText("Menu");
        jPanel3.add(lblMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 90, 50));

        jPanel4.setBackground(new java.awt.Color(102, 0, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/facadeshop/icons/compras.png"))); // NOI18N
        btnCompras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCompras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnComprasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnComprasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnComprasMouseExited(evt);
            }
        });
        jPanel4.add(btnCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(-130, 20, 180, 40));

        btnProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/facadeshop/icons/productos.png"))); // NOI18N
        btnProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProductosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProductosMouseExited(evt);
            }
        });
        jPanel4.add(btnProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(-126, 120, 180, 40));

        btnVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/facadeshop/icons/ventas.png"))); // NOI18N
        btnVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVentasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVentasMouseExited(evt);
            }
        });
        jPanel4.add(btnVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(-126, 70, 180, 40));

        btnProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/facadeshop/icons/proveedores.png"))); // NOI18N
        btnProveedores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProveedoresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProveedoresMouseExited(evt);
            }
        });
        btnProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedoresActionPerformed(evt);
            }
        });
        jPanel4.add(btnProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(-126, 170, 180, 40));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 190, 230));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/facadeshop/icons/Home48.png"))); // NOI18N
        jLabel8.setToolTipText("Inicio");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 540, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/facadeshop/icons/exit32.png"))); // NOI18N
        jLabel6.setToolTipText("Salir");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 0, 30, 50));
        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, -30, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 55));

        jpnIdCompra2.setBackground(new java.awt.Color(102, 0, 0));
        jpnIdCompra2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIdCompra2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblIdCompra2.setForeground(new java.awt.Color(255, 255, 255));
        lblIdCompra2.setText("Id Compra:");
        jpnIdCompra2.add(lblIdCompra2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 80, 30));

        getContentPane().add(jpnIdCompra2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 100, 30));

        txtIdCompra2.setText("001");
        txtIdCompra2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdCompra2ActionPerformed(evt);
            }
        });
        getContentPane().add(txtIdCompra2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 50, 30));

        jpnProveedor2.setBackground(new java.awt.Color(102, 0, 0));
        jpnProveedor2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblProveedor2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblProveedor2.setForeground(new java.awt.Color(255, 255, 255));
        lblProveedor2.setText("Proveedor:");
        jpnProveedor2.add(lblProveedor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 90, 30));

        getContentPane().add(jpnProveedor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 100, 30));

        txtProveedor2.setText("Pollo Indio");
        getContentPane().add(txtProveedor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 150, 30));

        jpnCabezeraTablaCompra2.setBackground(new java.awt.Color(102, 0, 0));
        jpnCabezeraTablaCompra2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIdProducto2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblIdProducto2.setForeground(new java.awt.Color(255, 255, 255));
        lblIdProducto2.setText("Id Producto");
        jpnCabezeraTablaCompra2.add(lblIdProducto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 80, 20));

        lblProducto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblProducto.setForeground(new java.awt.Color(255, 255, 255));
        lblProducto.setText("Producto");
        jpnCabezeraTablaCompra2.add(lblProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 70, 20));

        lblCantidad2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCantidad2.setForeground(new java.awt.Color(255, 255, 255));
        lblCantidad2.setText("Cantidad");
        jpnCabezeraTablaCompra2.add(lblCantidad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 60, 20));

        lblCosto2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCosto2.setForeground(new java.awt.Color(255, 255, 255));
        lblCosto2.setText("Costo");
        jpnCabezeraTablaCompra2.add(lblCosto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 0, 60, 20));

        getContentPane().add(jpnCabezeraTablaCompra2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 830, 20));

        tblCompra2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCompra2.setEnabled(false);
        jScrollPane1.setViewportView(tblCompra2);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 830, 230));

        jpnFecha2.setBackground(new java.awt.Color(102, 0, 0));
        jpnFecha2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFecha2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblFecha2.setForeground(new java.awt.Color(255, 255, 255));
        lblFecha2.setText("Fecha:");
        jpnFecha2.add(lblFecha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 70, 30));

        getContentPane().add(jpnFecha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 70, 30));

        jpnIdCompra3.setBackground(new java.awt.Color(102, 0, 0));
        jpnIdCompra3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIdCompra3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblIdCompra3.setForeground(new java.awt.Color(255, 255, 255));
        lblIdCompra3.setText("Id Compra:");
        jpnIdCompra3.add(lblIdCompra3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 80, 30));

        getContentPane().add(jpnIdCompra3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 100, 30));

        jpnIdCompra4.setBackground(new java.awt.Color(102, 0, 0));
        jpnIdCompra4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIdCompra4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblIdCompra4.setForeground(new java.awt.Color(255, 255, 255));
        lblIdCompra4.setText("Id Compra:");
        jpnIdCompra4.add(lblIdCompra4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 80, 30));

        getContentPane().add(jpnIdCompra4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 100, 30));

        txtFecha2.setText("11/03/17");
        getContentPane().add(txtFecha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, 140, 30));

        jpnTotal2.setBackground(new java.awt.Color(102, 0, 0));
        jpnTotal2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTotal2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblTotal2.setForeground(new java.awt.Color(255, 255, 255));
        lblTotal2.setText("Total:");
        jpnTotal2.add(lblTotal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 40));

        getContentPane().add(jpnTotal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 520, 80, 40));

        txtTotal2.setText("$");
        getContentPane().add(txtTotal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 520, 100, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void btnComprasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComprasMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnComprasMouseClicked

    private void btnComprasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComprasMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnComprasMouseEntered

    private void btnComprasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComprasMouseExited
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnComprasMouseExited

    private void btnProductosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductosMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnProductosMouseEntered

    private void btnProductosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductosMouseExited
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnProductosMouseExited

    private void btnVentasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVentasMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnVentasMouseEntered

    private void btnVentasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVentasMouseExited
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnVentasMouseExited

    private void btnProveedoresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProveedoresMouseEntered
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnProveedoresMouseEntered

    private void btnProveedoresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProveedoresMouseExited
        // TODO add your handling code here:
        

    }//GEN-LAST:event_btnProveedoresMouseExited

    private void btnProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProveedoresActionPerformed

    private void txtIdCompra2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdCompra2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdCompra2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFRDetalleCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFRDetalleCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFRDetalleCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFRDetalleCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFRDetalleCompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCompras;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnProveedores;
    private javax.swing.JButton btnVentas;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpnCabezeraTablaCompra2;
    private javax.swing.JPanel jpnFecha2;
    private javax.swing.JPanel jpnIdCompra2;
    private javax.swing.JPanel jpnIdCompra3;
    private javax.swing.JPanel jpnIdCompra4;
    private javax.swing.JPanel jpnProveedor2;
    private javax.swing.JPanel jpnTotal2;
    private javax.swing.JLabel lblCantidad2;
    private javax.swing.JLabel lblCosto2;
    private javax.swing.JLabel lblFecha2;
    private javax.swing.JLabel lblIdCompra2;
    private javax.swing.JLabel lblIdCompra3;
    private javax.swing.JLabel lblIdCompra4;
    private javax.swing.JLabel lblIdProducto2;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JLabel lblProducto;
    private javax.swing.JLabel lblProveedor2;
    private javax.swing.JLabel lblTotal2;
    private javax.swing.JTable tblCompra2;
    private javax.swing.JTextField txtFecha2;
    private javax.swing.JTextField txtIdCompra2;
    private javax.swing.JTextField txtProveedor2;
    private javax.swing.JTextField txtTotal2;
    // End of variables declaration//GEN-END:variables
}
