/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import AppPackage.AnimationClass;
import javax.swing.ImageIcon;

/**
 *
 * @author User
 */
public class Slide extends javax.swing.JFrame {

    /**
     * Creates new form Slide
     */
    AnimationClass AC = new AnimationClass();
    public Slide() {
        initComponents();
        SlideShow();
    }
    public void SlideShow(){
        new Thread()
        {
            int count;
            @Override
            public void run()
            {
                try
                {
                    while(true)
                    {
                        switch(count)
                        { 
                            case 0:
                                ImageIcon II = new ImageIcon(getClass().getResource("/images/Fondo1.jpg"));
                                lblPrincipal.setIcon(II);
                                Thread.sleep(3000);
                                AC.jLabelXLeft(0, -840, 20, 7, lblPrincipal);
                                AC.jLabelXLeft(840, 0, 20, 7, lblSecundario);
                                count = 1;
                                break;
                                   
                            case 1:
                                ImageIcon II2 = new ImageIcon(getClass().getResource("/images/Fondo2.jpg"));
                                lblSecundario.setIcon(II2);
                                Thread.sleep(3000);
                                AC.jLabelXRight(-840, 0, 20, 7, lblPrincipal);
                                AC.jLabelXRight(0, 840, 20, 7, lblSecundario);
                                count = 2;
                                break;
                                
                            case 2:
                                ImageIcon II3 = new ImageIcon(getClass().getResource("/images/Fondo3.jpg"));
                                lblPrincipal.setIcon(II3);
                                Thread.sleep(3000);
                                AC.jLabelXLeft(0, -840, 20, 7, lblPrincipal);
                                AC.jLabelXLeft(840, 0, 20, 7, lblSecundario);
                                count = 3;
                                break;
                                   
                            case 3:
                                ImageIcon II4 = new ImageIcon(getClass().getResource("/images/Fondo1.jpg"));
                                lblSecundario.setIcon(II4);
                                Thread.sleep(3000);
                                AC.jLabelXRight(-840, 0, 20, 7, lblPrincipal);
                                AC.jLabelXRight(0, 840, 20, 7, lblSecundario);
                                count = 4;
                                break;   
                                
                            case 4:
                                ImageIcon II5 = new ImageIcon(getClass().getResource("/images/Fondo2.jpg"));
                                lblPrincipal.setIcon(II5);
                                Thread.sleep(3000);
                                AC.jLabelXLeft(0, -840, 20, 7, lblPrincipal);
                                AC.jLabelXLeft(840, 0, 20, 7, lblSecundario);
                                count = 5;
                                break;
                                   
                            case 5:
                                ImageIcon II6 = new ImageIcon(getClass().getResource("/images/Fondo3.jpg"));
                                lblPrincipal.setIcon(II6);
                                Thread.sleep(3000);
                                AC.jLabelXRight(-840, 0, 20, 7, lblPrincipal);
                                AC.jLabelXRight(0, 840, 20, 7, lblSecundario);
                                count = 0;
                                break;
                                
                            
                        }
                    }
                    
                }
                catch(Exception e)
                {
                    
                }
            }
        }.start();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPrincipal = new javax.swing.JLabel();
        lblSecundario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(840, 472));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Fondo1.jpg"))); // NOI18N
        getContentPane().add(lblPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 472));

        lblSecundario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Fondo3.jpg"))); // NOI18N
        getContentPane().add(lblSecundario, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 0, 840, 472));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Slide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Slide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Slide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Slide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Slide().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblPrincipal;
    private javax.swing.JLabel lblSecundario;
    // End of variables declaration//GEN-END:variables
}
